### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by wwww-wwww** [rndusr/torf#28]
On linux, the default limit is 1024 open files `ulimit -n`
This error can be temporarily remedied by running `ulimit -n 5000` or whatever number

I imagine it's not a simple fix within torf, so this is mainly for anyone else that runs into this problem.

```
Traceback (most recent call last):
  File "/home/w/.local/lib/python3.10/site-packages/torf/_stream.py", line 382, in _get_open_file
    self._open_files[filepath] = open(filepath, 'rb')
OSError: [Errno 24] Too many open files: "FILENAME"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/h/convert/out/torrent.py", line 35, in <module>
    t.generate(callback=cb, interval=0.5)
  File "/home/w/.local/lib/python3.10/site-packages/torf/_torrent.py", line 1114, in generate
    piece_hashes = collector.collect()
  File "/home/w/.local/lib/python3.10/site-packages/torf/_generate.py", line 337, in collect
    self._collect(*task)
  File "/home/w/.local/lib/python3.10/site-packages/torf/_generate.py", line 367, in _collect
    maybe_cancel = self._callback(
  File "/home/w/.local/lib/python3.10/site-packages/torf/_generate.py", line 427, in __call__
    return self._intervaled_callback(piece_index, pieces_done, pieces_total,
  File "/home/w/.local/lib/python3.10/site-packages/torf/_generate.py", line 412, in __call__
    return self._callback(*args)
  File "/home/w/.local/lib/python3.10/site-packages/torf/_generate.py", line 455, in _call_callback
    raise exceptions[0]
  File "/home/w/.local/lib/python3.10/site-packages/torf/_stream.py", line 445, in iter_pieces
    fh = self._get_open_file(filepath)
  File "/home/w/.local/lib/python3.10/site-packages/torf/_stream.py", line 384, in _get_open_file
    raise error.ReadError(e.errno, filepath)
torf._errors.ReadError: FILENAME: Too many open files
```

**Comment by rndusr** [comment]
Can you explain how I can reproduce this error?
Do you have >1024 really small files?

**Comment by wwww-wwww** [comment]
Yes. I happen to be making a torrent with 1085 files. (music)

**Comment by rndusr** [comment]
Should be fixed.

Can you check out the latest master and confirm?

**Comment by wwww-wwww** [comment]
That works, thanks.

**Comment by rndusr** [comment]
Thanks for reporting back. I made a bugfix release.
